[phases.setup]
nixPkgs = ["python3", "nodejs", "ffmpeg"]

[phases.install]
cmds = [
    "cd frontend && npm install --include=dev",
    "cd backend && pip install -r requirements.railway.txt"
]

[phases.build]
cmds = ["cd frontend && npm run build && echo 'BUILD COMPLETE' && ls -la dist"]

[start]
cmd = "echo 'CONTENTS OF FRONTEND:' && ls -la /app/frontend && cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
