[nix]
channel = "stable-24_11"

[phases.build]
cmds = ["echo 'Building backend'", "pip install -r requirements.railway.txt"]

[phases.start]
cmd = ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "$PORT"]

[variables]
PYTHONPATH = "${ env:RAILWAY_SOURCE_DIR }"
