[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg", "libsndfile"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
