services:
  - type: web
    name: lyrics-chord-detector-api
    runtime: python
    plan: free
    buildCommand: cd backend && bash install.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
